name = "Assignment"
uuid = "30268ba6-d258-4c5c-9bcf-b5809bbf81b5"
authors = ["Matthew Griffiths <matthewghgriffiths@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "1.18, 2, 0.18"
julia = "1"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Combinatorics"]
